version: "3.8"

networks:
  overtimer-net:
    name: overtimer-net
    driver: bridge  

volumes:
  db_volume: 

services:
  overtimer-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "AppSettings__DB_CONN=host=db;port=5432;database=ClockifyClone;username=postgres;password=password"
    volumes:
      - ~/.aspnet/https:/https:ro    
    ports:
      - 8045:8045
    depends_on:
      - db    
    restart: on-failure
    networks:
      - overtimer-net

  overtimer-api-migrations:
    build:
      context: .
      dockerfile: MigrationDockerfile
    depends_on:
      - db
    restart: on-failure
    environment:
      - "AppSettings__DB_CONN=host=db;port=5432;database=ClockifyClone;username=postgres;password=password"
    networks:
      - overtimer-net
    entrypoint: ./efbundle --connection "host=db;port=5432;database=ClockifyClone;username=postgres;password=password"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ClockifyClone
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "2346:5432"    
    networks:
      - overtimer-net